openapi: 3.1.0
info:
  title: Exemplo de API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retorna uma mensagem de saudação
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:us-east-1:123456789012:function:helloFunction
